server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /appey

spring:
  application:
    name: ey-code
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
mybatis:
  mapper-locations:
      - classpath:mapper/*.xml
      - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

